### ISSUE TITLE
The fontspec package is necessary?

### ISSUE THREAD

**Issue by PonderLY** [wilx/tweet2latex#1]
Thanks for sharing this useful tool. The fontspec package requires either XeTeX or LuaTeX to function, but I need to display twitter record in my paper, which uses PDFLaTeX. I wonder if it is possible to define the tweet environment without fontspec package. If possible, could you please give me some instructions on how to modify the definition?

**Comment by wilx** [comment]
I have pushed a small change to the script and I have added example document compilable with PDFLaTeX. However, its utility with PDFLaTeX is lessened. It does not support emoji out of the box. You could try to adjust the tweet environment definition and use [coloremoji.sty](https://github.com/alecjacobson/coloremoji.sty). But that package is not on CTAN, you would have to install it manually.

**Comment by PonderLY** [comment]
Thanks for your quick response. Following your instructions, I succeed to display the tweet in my paper and it looks pretty well. By the way, for my usage of your tools, is it OK to cite this repository in the paper? Additionally, I have two more suggestions for this environment. One is to add a title for each tweet, something like \caption for image or table. The other is to number each tweet automatically for cross reference in the paper, something like \ref or \label. I try to modify the definition but I am not good at this. Could you please help me out ?

**Comment by wilx** [comment]
Alright. I have just pushed some changes that add caption and demonstrate how to use references using `cleveref`. This is the best I can do at the moment.
